CRUD/CRUD/Controllers/PostController.cs
using CRUD.Areas.Identity.Data;
using CRUD.Data;
using CRUD.Models;
using CRUD.Services.Contracts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace CRUD.Controllers
{
    [Authorize]
    public class PostController : Controller
    {
        public IPostServices postServices;

        public PostController(IPostServices postServices)
        {
            this.postServices = postServices;
        }
        public IActionResult Index()
        {
            var posts = this.postServices.GetUserPosts();
            return View(posts);
        }

        public IActionResult Details(string Slug)
        {
            PostViewModel targetPost = this.postServices.GetPostDetails(Slug);
            return View(targetPost);
        }

        [HttpGet]
        public IActionResult Create()
        {
            PostViewModel newPost = new PostViewModel();
            newPost.AuthorUserId = this.postServices.GetCurrentUser();
            return View(newPost);
        }

        [HttpPost]
        public IActionResult Create(PostViewModel post)
        {
            if (ModelState.IsValid)
            {
                this.postServices.CreateNewPost(post);
                return RedirectToAction("Details", new { Slug = post.Slug });
            }
            else
            {
                post.AuthorUserId = this.postServices.GetCurrentUser();
                return View(post);
            }
        }

        [HttpGet]
        public IActionResult Edit(string Slug)
        {
            PostViewModel targetPost = this.postServices.GetPostDetails(Slug);
            return View(targetPost);
        }

        [HttpPost]
        public IActionResult Edit(PostViewModel newPost)
        {
            if (ModelState.IsValid)
            {
                this.postServices.EditPost(newPost);
                return RedirectToAction("Details", new { Slug = newPost.Slug });
            }
            else
            {
                return View(newPost);
            }
        }

        public IActionResult Delete(string Slug)
        {
            this.postServices.DeletePost(Slug);
            return RedirectToAction("Index");
        }
    }
}

CRUD/CRUD/Controllers/UserController.cs
using CRUD.Areas.Identity.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace CRUD.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;

        public UserController(UserManager<ApplicationUser> userManager)
        {
            this.userManager = userManager;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var users = this.userManager.Users;
            return View(users);
        }
    }
}

CRUD/CRUD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CRUD</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CRUD.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CRUD</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">All Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Post" asp-action="Index">Your Posts</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial.cshtml"></partial>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - CRUD - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>